### ISSUE TITLE
ConnectionReset Error While Downloading Assets

### ISSUE THREAD

**Issue by namelessshere** [Voxelum/x-minecraft-launcher#338]
Launcher successfully download every aspect of the game except assets. After some time of downloading assets I constantly get a `ConnectionReset` error, though everything is fine with my internet connection.

<details open>
  <summary>Error Message</summary>
  <pre><code>[{"error":"ConnectionReset","url":"https://resources.download.minecraft.net/2b/2bd6b2b46db5b6969808b3bd3d62e7427d63c264","metadata":{"url":"https://resources.download.minecraft.net/2b/2bd6b2b46db5b6969808b3bd3d62e7427d63c264","isAcceptRanges":true,"contentLength":315459,"lastModified":"Mon, 02 Mar 2020 21:08:24 GMT","eTag":"\"16d6e1e65e803c54f3772fb0844f9cf9\""},"headers":{},"destination":"D:\\.xmcl\\assets\\objects\\2b\\2bd6b2b46db5b6969808b3bd3d62e7427d63c264","retryAttempt":1,"segments":[{"start":15852,"end":315458}],"segmentErrors":[{"errno":-4077,"code":"ECONNRESET","syscall":"read"}],"name":"DownloadError","message":"The download failed! ConnectionReset","stack":"DownloadError: The download failed! ConnectionReset\n at Download.processDownload (C:\\Users\\namel\\Downloads\\xmcl-0.30.5-win32-x64\\resources\\app.asar\\dist\\index.js:152:110215)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async Download.downloadUrl (C:\\Users\\namel\\Downloads\\xmcl-0.30.5-win32-x64\\resources\\app.asar\\dist\\index.js:152:110760)\n at async Download.start (C:\\Users\\namel\\Downloads\\xmcl-0.30.5-win32-x64\\resources\\app.asar\\dist\\index.js:152:111503)\n at async InstallAssetTask.runTask (C:\\Users\\namel\\Downloads\\xmcl-0.30.5-win32-x64\\resources\\app.asar\\dist\\index.js:152:90638)"},{"errno":-4083,"code":"EBADF","syscall":"ftruncate","message":"EBADF: bad file descriptor, ftruncate","stack":"Error: EBADF: bad file descriptor, ftruncate","name":"Error"},{"errno":-4083,"code":"EBADF","syscall":"ftruncate","message":"EBADF: bad file descriptor, ftruncate","stack":"Error: EBADF: bad file descriptor, ftruncate","name":"Error"}]</code></pre>
</details>

**To Reproduce**

Steps to reproduce the behaviour:

1. Open the **Profiles** tab and create/select a profile with 1.19.2 version (tried on 1.18.2 as well),
2. Click the **Launch** button.
3. Open the Task Manager within the launcher.

**Expected Behaviour**

Assets being successfully downloaded and the game being launched.

**Screenshots**

![Error](https://i.imgur.com/Qlzvorr.png)

**Environment**
 - OS: Windows 11
 - Version: 22H2 (build 25182.1000)

**Comment by ci010** [comment]
Now in #348, we swap the download core, and download process can be retried easily. This kind of errors also have corresponding i18n message for user
