### ISSUE TITLE
Archlinuxarm arm64 AppImage无法启动

### ISSUE THREAD

**Issue by Xunflash** [Voxelum/x-minecraft-launcher#434]
Archlinuxarm arm64 AppImage无法启动
**To Reproduce**

chmod +x ./xmcl-0.35.5-arm64.AppImage
./xmcl-0.35.5-arm64.AppImage --no-sandbox

**Expected behavior**
正常启动

**Screenshots**

**Environment**
 - OS: Archlinuxarm
 - Version latest

**Additional context**
```
Fail to require native node module /home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node
Error: /tmp/.mount_xmcl-0S536hx/resources/app.asar.unpacked/node.napi.glibc.node: æ æ³æå¼å±äº«å¯¹è±¡æä»¶: æ²¡æé£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node (/tmp/.mount_xmcl-0S536hx/resources/app.asar/node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node:2:243)
    at /tmp/.mount_xmcl-0S536hx/resources/app.asar/index.js:1:643 {
  code: 'ERR_DLOPEN_FAILED'
}

(xmcl:54754): Gtk-WARNING **: 01:56:46.746: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(xmcl:54754): Gtk-WARNING **: 01:56:46.746: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
[54791:0512/015647.873504:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: 没有那个文件或目录 (2)
[54791:0512/015647.874103:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: 没有那个文件或目录 (2)
[54791:0512/015647.874571:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: 没有那个文件或目录 (2)

```

**Comment by ci010** [comment]
啊因为我没有arm64设备这个没法测，不过我看了下我build出来的文件，貌似是这个依赖放错了
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/89978956-3d7d-4fec-a823-1908bedfdfd8)

把 glib 这个文件覆盖现在的 glibc，如果没法搞可以等我的开发构建。

**Comment by Xunflash** [comment]
非常感谢！目前这个版本已经能启动了，但是依然有这个之前的报错
`[54791:0512/015647.873504:ERROR:gbm_wrapper.cc(293)] Failed to export buffer to dma_buf: 没有那个文件或目录 (2)
`
并且勾选1.16.5,fabric后下载报错
```
(node:2794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(landed) listeners added to [ClassicLevel]. Use emitter.setMaxListeners() to increase limit
(Use `xmcl --trace-warnings ...` to show where the warning was created)
Checking for update
Error: Error: ENOENT: no such file or directory, open '/home/kupfer/xmcl/resources/app-update.yml'
[CACHE] GET https://api.xmcl.app/latest?version=v0.35.5&prerelease=false -> expired, try to request with headers {"Accept-Language":"zh-CN","user-agent":"voxelum/x_minecraft_launcher/0.35.5 (xmcl.app)"}
[CACHE] GET https://download.mcbbs.net/optifine/versionList -> expired, try to request with headers {"user-agent":"voxelum/x_minecraft_launcher/0.35.5 (xmcl.app)"}
[CACHE] GET https://download.mcbbs.net/fabric-meta/v2/versions/yarn -> expired, try to request with headers {"user-agent":"voxelum/x_minecraft_launcher/0.35.5 (xmcl.app)"}
[CACHE] GET https://authserver.ely.by/api/authlib-injector -> expired, try to request with headers {"user-agent":"voxelum/x_minecraft_launcher/0.35.5 (xmcl.app)"}
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
[CACHE] GET https://download.mcbbs.net/fabric-meta/v2/versions/loader -> expired, try to request with headers {"user-agent":"voxelum/x_minecraft_launcher/0.35.5 (xmcl.app)"}
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
(node:2794) UnhandledPromiseRejectionWarning: Error: Upnp action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping failed: 500
    at Device.run (/home/kupfer/xmcl/xmcl/packages/nat-api/lib/device.ts:174:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UpnpClient.map (/home/kupfer/xmcl/xmcl/packages/nat-api/lib/upnp.ts:97:5)
    at NatService.map (/home/kupfer/xmcl/xmcl-runtime/lib/services/NatService.ts:47:5)
    at async Promise.all (index 1)
    at initNat (/home/kupfer/xmcl/xmcl-runtime/lib/services/PeerService.ts:112:11)
(node:2794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
http://192.168.1.1:5000/rootDesc.xml
[2866:0512/231404.989801:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(node:2794) UnhandledPromiseRejectionWarning: RPC_COULD_NOT_CONNECT: Could not connect
    at /home/kupfer/xmcl/xmcl/packages/discord-rpc/transport/IPC.ts:142:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
[2866:0512/231415.170316:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[2866:0512/231415.176690:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(node:2794) UnhandledPromiseRejectionWarning: RPC_COULD_NOT_CONNECT: Could not connect
    at /home/kupfer/xmcl/xmcl/packages/discord-rpc/transport/IPC.ts:142:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:2794) UnhandledPromiseRejectionWarning: RPC_COULD_NOT_CONNECT: Could not connect
    at /home/kupfer/xmcl/xmcl/packages/discord-rpc/transport/IPC.ts:142:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:2794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)

```

**Comment by ci010** [comment]
@Xunflash  我完全没了解过 mc 在 arm 下的表现，你知道这个 `liblwjgl.so` 是在哪个 jar 文件解压的么

**Comment by Xunflash** [comment]
这个我也不太清楚，但是或许可以参考一下这个pr
https://github.com/huanghongxun/HMCL/pull/1610
另外附上一个用hmcl启动的启动脚本，可以顺利启动并且帧率也很稳
[start.txt](https://github.com/Voxelum/x-minecraft-launcher/files/11474265/start.txt)

**Comment by ci010** [comment]
@Xunflash 你能看一下你 1.16.5-natives 文件夹里现在有什么文件么，就位于 `versions/1.16.5/1.16.4-natives`

**Comment by Xunflash** [comment]
@ci010 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/71567536/1fd5228b-d2b2-4a90-a491-218ace2957af)
这明显是有问题了，这一块都是x64的链接库，可能需要在arm上重新编译
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/71567536/e1e873ae-86e8-4bfd-906b-4c531893ed8c)
另外这个位置是有文件的

**Comment by ci010** [comment]
> @ci010 ![image](https://user-images.githubusercontent.com/71567536/239750711-1fd5228b-d2b2-4a90-a491-218ace2957af.png) 这明显是有问题了，这一块都是x64的链接库，可能需要在arm上重新编译 ![image](https://user-images.githubusercontent.com/71567536/239750809-e1e873ae-86e8-4bfd-906b-4c531893ed8c.png) 另外这个位置是有文件的

这个新开 issue 把，我看 hmcl 是做了自定义 arm64 lib 下载，回头搞一下
