### ISSUE TITLE
ARM64 library auto replacement

### ISSUE THREAD

**Issue by ci010** [Voxelum/x-minecraft-launcher#441]
Should auto replace the Minecraft libraries in arm64

See https://github.com/huanghongxun/HMCL/pull/1610

**Comment by Cubik65536** [comment]
> Should we close this bug since we've found that the ARM64 library is supported?

Is it working now with X-Minecraft-Launcher? I'm using it with an Apple Silicon machine and LWJGL library still can't be properly loaded. LOG:

``` log
[19:57:07] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.22
[19:57:07] [main/INFO]: Loading 3 mods:
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.18.2
[19:57:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/cubik65536/.xmcl/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:57:09] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[19:57:09] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[19:57:09] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[19:57:10] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2394) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2389) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib [in thread "Render thread"]
	at org.lwjgl.system.Library.loadSystem(Library.java:147) ~[lwjgl-3.2.1.jar:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:67) ~[lwjgl-3.2.1.jar:?]
	at org.lwjgl.system.Library.<clinit>(Library.java:50) ~[lwjgl-3.2.1.jar:?]
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97) ~[lwjgl-3.2.1.jar:?]
	at net.minecraft.class_311.<clinit>(class_311.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.<init>(class_287.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<init>(class_289.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<init>(class_289.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_289.<clinit>(class_289.java:11) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:46) ~[1.18.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:194) ~[1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more
```

**Comment by ci010** [comment]
Close #586
