### ISSUE TITLE
Linux 下无法直接用 app.asar 启动

### ISSUE THREAD

**Issue by zhaose233** [Voxelum/x-minecraft-launcher#473]
用 asar 文件启动 xmcl 会报错，并且无法启动

```
Fail to require native node module /home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node
Error: /tmp/app-0.35.19-linux.asar.unpacked/node.napi.glibc.node: ç
                                                                   ¡æ³éå
±ç¨ç	©ä»¶: æ²æ	æ­¤ä¸æªæ¡æç

    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node (/tmp/app-0.35.19-linux.asar/node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/prebuilds/linux-x64/node.napi.glibc.node:2:243)
    at /tmp/app-0.35.19-linux.asar/index.js:1:643 {
  code: 'ERR_DLOPEN_FAILED'
}
Fail to require native node module /home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/node-datachannel@0.4.1/node_modules/node-datachannel/build/Release/node_datachannel.node
Error: /tmp/app-0.35.19-linux.asar.unpacked/node_datachannel.node: ç
                                                                    ¡æ³éå
±ç¨ç	©ä»¶: æ²æ	æ­¤ä¸æªæ¡æç

    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/node-datachannel@0.4.1/node_modules/node-datachannel/build/Release/node_datachannel.node (/tmp/app-0.35.19-linux.asar/node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/node-datachannel@0.4.1/node_modules/node-datachannel/build/Release/node_datachannel.node:2:244)
    at /tmp/app-0.35.19-linux.asar/index.js:1:643 {
  code: 'ERR_DLOPEN_FAILED'
}
Fail to require native node module /home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/keytar@7.9.0/node_modules/keytar/build/Release/keytar.node
Error: /tmp/app-0.35.19-linux.asar.unpacked/keytar.node: ç
                                                          ¡æ³éå
±ç¨ç	©ä»¶: æ²æ	æ­¤ä¸æªæ¡æç

    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/keytar@7.9.0/node_modules/keytar/build/Release/keytar.node (/tmp/app-0.35.19-linux.asar/node-file:/home/runner/work/x-minecraft-launcher/x-minecraft-launcher/node_modules/.pnpm/keytar@7.9.0/node_modules/keytar/build/Release/keytar.node:2:214)
    at /tmp/app-0.35.19-linux.asar/index.js:1:643 {
  code: 'ERR_DLOPEN_FAILED'
}
App threw an error during load
TypeError: binding.db_init is not a function
    at new ClassicLevel (/node_modules/.pnpm/classic-level@1.3.0/node_modules/classic-level/index.js:44:30)
    at new NetworkManager (/xmcl-runtime/lib/managers/NetworkManager.ts:41:19)
    at new LauncherApp (/xmcl-runtime/lib/app/LauncherApp.ts:158:27)
    at new ElectronLauncherApp (/tmp/main/ElectronLauncherApp.ts:80:5)
    at Object.<anonymous> (/tmp/main/index.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
(node:56661) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:56661) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:56661) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:56661) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
```

**To Reproduce**

下载 app-\<version\>-linux.asar 文件，直接 `electron XXX.asar` 执行，就会报错

**Expected behavior**
能够正常使用祼 asar 运行（在 0.34.XX 版本时是可以的，似乎是在 0.35 之后才出现的问题）

**Environment**
 - OS: Arch Linux
 - Version rolling

**Additional context**
在 0.34.XX 版本时是可以的，似乎是在 0.35 之后才出现的问题

**Comment by ci010** [comment]
居然还有这么用的我确实没想到，有没有可能是electron版本不匹配？还有 `node.napi.glibc.node` 这个文件有么

**Comment by zhaose233** [comment]
我试了几个 electron 版本似乎都不太行，electron19, 22, 25 都试过

**Comment by ci010** [comment]
>.39.x 应该更方便了，之前其实还是需要unpack几个文件到asar外面，现在不需要了。所以理论上asar和electron版本对了就行。新的electron 版本是 27。之后 28 稳定了打算升级 28（因为 28 允许 ESM，是个重大升级）
