### ISSUE TITLE
error installing on launcher

### ISSUE THREAD

**Issue by yolamc** [Voxelum/x-minecraft-launcher#597]
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/14548095/report.zip)

when i try to install version 1.20.4 nothing happens and when i check settings it tells me Response with 502
full message: Response with 502
      MinecraftVersionListError: Response with 502
    at getJson (/750/index.js:224:12630)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at VersionMetadataService.getMinecraftVersionList (/750/index.js:224:14632)
    at handleServiceCall (/750/index.js:230:32084)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88640)
    
this is my first time using this launcher

**Comment by ShadowAndNitrix** [comment]
Same Happens With Mine But A Lil Diff Tho
