### ISSUE TITLE
empty “game over” menu

### ISSUE THREAD

**Issue by SlenGuard** [Voxelum/x-minecraft-launcher#631]
please help

I downloaded the launcher, made a version, and when I wanted to launch it, the window “game crashed” appears and it's empty. I reinstalled it several times, but all the times there were some problems with launching minecraft, I really want to use this launcher. i will be grateful for your help.

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/137446561/dab09b1e-d687-4bc9-b9ad-813ff9d725f5)

I tried to log in from another version and the error changed to this:
[authlib-injector] [INFO] Logging file: D:\xlauncher з установки\instances\темст\authlib-injector.log

[authlib-injector] [INFO] Version: 1.2.5

[authlib-injector] [INFO] Authentication server: https://authserver.ely.by/api/authlib-injector

[authlib-injector] [INFO] Disabled Mojang namespace

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]

[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]

[authlib-injector] [INFO] Httpd is running on port 57558

[authlib-injector] [INFO] Transformed [fiv] with [Constant URL Transformer]

[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]

[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo] with [Yggdrasil Public Key Transformer]

[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]

[authlib-injector] [INFO] Transformed [by.ely.authlib.ElyTextureService] with [Constant URL Transformer]

**Comment by ci010** [comment]
Try to disable authlib-injector and ely.by in your instance setting to see if that helps.

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/86d65d63-fb33-4c61-9cf2-c5d1a2a3fc38)

**Comment by SlenGuard** [comment]
didn't help, still an empty menu 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/137446561/1db4693a-4d9a-492b-89c6-68ec32625ab7)

**Comment by SlenGuard** [comment]
I tried to turn it off in the settings, but it didn't help

**Comment by SlenGuard** [comment]
I tried to run another version again and there is the same error:

[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

Exception in thread "main" 
java.lang.UnsatisfiedLinkError: Failed to locate library: glfw.dll

	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.Library.loadNative(Library.java:327)

	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.Library.loadNative(Library.java:224)

	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:30)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.2.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initWindow(DisplayWindow.java:344)

	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.2.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.start(DisplayWindow.java:289)

	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.2.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initialize(DisplayWindow.java:151)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ImmediateWindowHandler.load(ImmediateWindowHandler.java:48)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.earlyInitialization(ModDirTransformerDiscoverer.java:43)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$18(TransformationServicesHandler.java:131)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:131)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by ci010** [comment]
Interesting... Can you generate a launcher report.zip and send it to me? Also what's your OS? If you are using linux, try to disable

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/03a445e7-59a1-4a9a-907e-baf2ab0db7f2)

Also, whatever your OS is, try to disable the "Replace Native Libraries"
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/0d8290b0-c50c-4dcc-ba66-3cf4accab006)

If you gives me `report.zip` will always help though.

**Comment by SlenGuard** [comment]
yay, I disabled it and everything worked, thanks a lot, just in case, here's the report.zip because before several reinstallations it complained about java not growing properly, maybe there are some other problems, thanks a lot
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/15287110/report.zip)

**Comment by SlenGuard** [comment]
and for some reason I don't have a “modpack market”, instead of it I have a regular background 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/137446561/22d738fd-ba9b-449e-99ed-2699ace5000a)

**Comment by ci010** [comment]
> and for some reason I don't have a “modpack market”, instead of it I have a regular background ![image](https://private-user-images.githubusercontent.com/137446561/329868241-22d738fd-ba9b-449e-99ed-2699ace5000a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzkxMjAsIm5iZiI6MTcxNTUzODgyMCwicGF0aCI6Ii8xMzc0NDY1NjEvMzI5ODY4MjQxLTIyZDczOGZkLWJhOWItNDQ5ZS05OWVkLTI2OTlhY2U1MDAwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxODMzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjU5MzA4YTcwOWZlNjFlODAwYTM3MTJhYmM3ODRhNjQ5NWNmY2VmNDJkMGU5OGNlYWNhYmRlMzVhZGI1ZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.is9vDpUTh730DMDWiTLOvmamj3zfXhiwqS-xJu-dzZg)

Try latest 0.44.5
