### ISSUE TITLE
Microsoft account

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [Voxelum/x-minecraft-launcher#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.45.2

### Operating System

Windows

### Architecture

x64

### Current Behavior

unable to log-in in microsoft account

### Expected Behavior

log-in sucefully

### Steps To Reproduce

with a microsoft account with a xobox profile
1. open loucher
2. log-in
3. se error: "Fail to login Xbox by Microsoft token. Please make sure you have a independent xbox account to your Microsoft account. Please try again."

### Anything else?

[report.zip](https://github.com/user-attachments/files/16730849/report.zip)

**Comment by ShadowAndNitrix** [comment]
HMMMMM, I Think Is Caused Because Either Dont Have an Xbox Acct Linked To Ur Google Account Or You Don't Own Minecraft On Your Microsoft Account, Idk This Is Just Speculation Tbh

**Comment by ShinobuKocho9906** [comment]
i have minecraft on microsoft account: 
<img width="960" alt="{DF0BEF12-C382-4DD6-9878-5B7CF5452D4F}" src="https://github.com/user-attachments/assets/6bb6db4a-e490-4e20-9627-067a7f3f3d40">(bought from MS store of windows 11)

i have not xbox account linked with google but is linked to microsoft account

**Comment by ShinobuKocho9906** [comment]
i have early request help on discord server but i don't found a solution (here: https://discord.com/channels/405213567118213121/1073220911106371626/threads/1273307038771970058)

**Comment by ci010** [comment]
> i have early request help on discord server but i don't found a solution (here: https://discord.com/channels/405213567118213121/1073220911106371626/threads/1273307038771970058)

Sorry I don't have much time recently. I've downloaded your report and I will take a look when I have time.

**Comment by ShinobuKocho9906** [comment]
ok

**Comment by ShadowAndNitrix** [comment]
Maybe Try Linking A Xbox Account To Ur Microsoft Account And See If It Works

**Comment by ShinobuKocho9906** [comment]
My "Xbox account" is early linked to Microsoft accounts because it was created from Microsoft account (as a profile from Xbox app accessing to Microsoft account not from Xbox web site). Not independently and linked to MS account after

**Comment by ShadowAndNitrix** [comment]
Then I Have No Idea

**Comment by ShinobuKocho9906** [comment]
in poly mc i receive this error: 
"Questo account Microsoft è posseduto da un minorenne e non è collegato a una famiglia.

Si prega di seguire [help.minecraft.net](https://help.minecraft.net/hc/en-us/articles/4403181904525) per impostare l'account."
<img width="960" alt="{494EBBA7-9EAB-42C9-8550-332E5DF8314A}" src="https://github.com/user-attachments/assets/51e5318b-7b37-4568-a9c5-993b9648bb56">

my account is not password protected bu protected with microsoft authenticartor app

**Comment by ShinobuKocho9906** [comment]
ok done the problem there are with latest version xmcl 0.46.1

**Comment by ShadowAndNitrix** [comment]
> ok done the problem there are with latest version xmcl 0.46.1

Nice To Hear.

**Comment by ci010** [comment]
Do you still have problem?

**Comment by ShinobuKocho9906** [comment]
Yes, but all Third party Minecraft java vouchers have a terror about the age, for example "Your account is a child account and must be added to a family to log in" or "`java.lang.RuntimeException: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
`"

**Comment by ShinobuKocho9906** [comment]
The origina Minecraft voucher work correctly on the same Minecraft account
