### ISSUE TITLE
Can't launch a server with modpacks

### ISSUE THREAD

**Issue by Cleverking2003** [Voxelum/x-minecraft-launcher#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.46.1

### Operating System

Windows

### Architecture

x64

### Current Behavior

When trying to start a server with a modpack, the launcher shows an error about a missing file (may differ between modpacks)

Antimatter Chemistry (and pretty much any 1.12.2+ pack I tested):
```{ "errno": -4058, "code": "ENOENT", "syscall": "open", "path": "D:\\.xmcl\\versions\\1.12.2-forge-14.23.5.2860\\server.json", "payload": [ "1.12.2-forge-14.23.5.2860", "server" ], "message": "ENOENT: no such file or directory, open 'D:\\.xmcl\\versions\\1.12.2-forge-14.23.5.2860\\server.json'", "stack": "Error: ENOENT: no such file or directory, open 'D:\\.xmcl\\versions\\1.12.2-forge-14.23.5.2860\\server.json'", "name": "Error", "serviceName": "InstallService", "serviceMethod": "installDependencies" }```

GT: New Horizons:

```[ { "exception": { "type": "httpException", "code": "UND_ERR_RESPONSE_STATUS_CODE", "method": "", "url": "http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-1.7.10-installer.jar", "statusCode": 404, "body": "" }, "name": "HTTPException", "message": "", "stack": "HTTPException: \n at serializeUndiciError (/947/index.js:166:40141)\n at serializeError (/947/index.js:166:40472)\n at Array.map (<anonymous>)\n at serializeError (/947/index.js:166:39930)\n at handleServiceCall (/947/index.js:243:26506)\n at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78381)" }, { "exception": { "type": "httpException", "code": "UND_ERR_RESPONSE_STATUS_CODE", "method": "", "url": "https://bmclapi2.bangbang93.com/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-1.7.10-installer.jar", "statusCode": 403, "body": "" }, "name": "HTTPException", "message": "", "stack": "HTTPException: \n at serializeUndiciError (/947/index.js:166:40141)\n at serializeError (/947/index.js:166:40472)\n at Array.map (<anonymous>)\n at serializeError (/947/index.js:166:39930)\n at handleServiceCall (/947/index.js:243:26506)\n at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78381)" }, { "exception": { "type": "httpException", "code": "UND_ERR_RESPONSE_STATUS_CODE", "method": "", "url": "https://repo1.maven.org/maven2/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-1.7.10-installer.jar", "statusCode": 404, "body": "" }, "name": "HTTPException", "message": "", "stack": "HTTPException: \n at serializeUndiciError (/947/index.js:166:40141)\n at serializeError (/947/index.js:166:40472)\n at Array.map (<anonymous>)\n at serializeError (/947/index.js:166:39930)\n at handleServiceCall (/947/index.js:243:26506)\n at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78381)" } ]```

(`http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-1.7.10-installer.jar` looks kinda sus bc the version number is duplicated. The correct URL is `http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar`)

### Expected Behavior

The launcher starts a server with a modpack.

### Steps To Reproduce

1. Install one of the modpacks mentioned above.
2. Press "Launch localhost server"
3. Get an error

**Comment by ShadowAndNitrix** [comment]
Ok, What Modpacks You Using?
Also I Think Local Hosting Might Cause That Issue, I Wouldn't Know I'm Still Using Version 0.35.17 XD
