### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by Aglimun** [Voxelum/x-minecraft-launcher#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

end version

### Operating System

Linux

### Architecture

x64

### Current Behavior

I logged in with my Elly by account, then I downloaded Minecraft 20.6, but I received the following warning:

Logging started at 2024-12-14T18:40:41.887937342Z
[authlib-injector] [ERROR] Invalid option: disabled
[authlib-injector] [DEBUG] A known exception has occurred
moe.yushi.authlibinjector.InitializationException: java.lang.IllegalArgumentException: No enum constant moe.yushi.authlibinjector.Config.FeatureOption.DİSABLED
	at moe.yushi.authlibinjector.Config.parseFeatureOption(Config.java:170)
	at moe.yushi.authlibinjector.Config.init(Config.java:182)
	at moe.yushi.authlibinjector.AuthlibInjector.bootstrap(AuthlibInjector.java:92)
	at moe.yushi.authlibinjector.Premain.initInjector(Premain.java:52)
	at moe.yushi.authlibinjector.Premain.premain(Premain.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.IllegalArgumentException: No enum constant moe.yushi.authlibinjector.Config.FeatureOption.DİSABLED
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at moe.yushi.authlibinjector.Config$FeatureOption.valueOf(Config.java:46)
	at moe.yushi.authlibinjector.Config.parseFeatureOption(Config.java:167)
	... 8 more

### Expected Behavior

start minecraft

### Anything else?

ely.by

**Comment by Peperehobbits01** [comment]
Could you name your issues and add the version of the launcher you used please, this would help to fix the bug.

**Comment by p2pproccessor** [comment]
I'm getting the same error on windows. v0.48.1 x-minecraft-launcher version and minecraft 1.21.4 and 1.21.3 version. I haven't tried other versions

[authlib-injector] [ERROR] Invalid option: disabled
[authlib-injector] [DEBUG] A known exception has occurred
moe.yushi.authlibinjector.InitializationException: java.lang.IllegalArgumentException: No enum constant moe.yushi.authlibinjector.Config.FeatureOption.DÝSABLED
	at moe.yushi.authlibinjector.Config.parseFeatureOption(Config.java:170)
	at moe.yushi.authlibinjector.Config.init(Config.java:182)
	at moe.yushi.authlibinjector.AuthlibInjector.bootstrap(AuthlibInjector.java:92)
	at moe.yushi.authlibinjector.Premain.initInjector(Premain.java:52)
	at moe.yushi.authlibinjector.Premain.premain(Premain.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.IllegalArgumentException: No enum constant moe.yushi.authlibinjector.Config.FeatureOption.DÝSABLED
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at moe.yushi.authlibinjector.Config$FeatureOption.valueOf(Config.java:46)
	at moe.yushi.authlibinjector.Config.parseFeatureOption(Config.java:167)
	... 8 more

**Comment by ci010** [comment]
This issue should be fixed I think
